services:
  frontend:
    build: ./frontend
    networks:
      - chatnet
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build: ./backend
    networks:
      - chatnet
    env_file:
      - .env
    models:
      - model-server

models:
  model-server: 
    model: ${LLM_MODEL_NAME}

networks:
  chatnet:

#----------------------------------------
# Old config. Use for 
# Compose v2.37
# Docker Desktop v4.43.0
#----------------------------------------
#services:
#  frontend:
#    build: ./frontend
#    networks:
#      - chatnet
#    ports:
#      - "3000:3000"
#    env_file:
#      - .env
#    depends_on:
#      - backend
#  backend:
#    build: ./backend
#    networks:
#      - chatnet
#    env_file:
#      - .env    
#    depends_on:
#      - model-server  
#  model-server:
#    provider:
#      type: model
#      options:
#        model: ${LLM_MODEL_NAME}
#networks:
#  chatnet: